#!/bin/sh

# Only run if gulp is available
if hash gulp 2>/dev/null; then
    gulp --gulpfile wouldyou/assets/gulpfile.js build --env=production
else
    echo "WARNING: gulp not found. Not running gulp build"
fi

# Should be inside virtual env
if [ "$VIRTUAL_ENV" != "" ]; then
    pip freeze > requirements.txt
else
    echo "WARNING: Not in virtualenv. Prerequisites not frozen."
fi