# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wouldyou', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileset',
            name='profiles',
            field=models.ManyToManyField(to='wouldyou.Profile'),
        ),
        migrations.AddField(
            model_name='action',
            name='profile_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wouldyou.ProfileSet'),
        ),
    ]
