# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wouldyou', '0004_auto_20160821_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileset',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
