# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wouldyou', '0008_player_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=255)),
                ('to', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='invite',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wouldyou.Player'),
        ),
    ]
