# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 09:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wouldyou', '0009_auto_20160823_0738'),
    ]

    operations = [
        migrations.RunSQL('DELETE FROM wouldyou_action'),

        migrations.RemoveField(
            model_name='action',
            name='user',
        ),
        migrations.AddField(
            model_name='action',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wouldyou.Player'),
            preserve_default=False,
        ),
    ]
