# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wouldyou', '0010_auto_20160823_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='picture',
            new_name='image',
        ),
    ]
