# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wouldyou', '0012_auto_20160824_0156'),
    ]

    operations = [
        migrations.RunSQL('DELETE FROM wouldyou_player'),

        migrations.CreateModel(
            name='PlayerAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='action',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='action',
            name='player',
        ),
        migrations.RemoveField(
            model_name='action',
            name='profile_set',
        ),
        migrations.RemoveField(
            model_name='action',
            name='verb',
        ),
        migrations.AddField(
            model_name='player',
            name='uid',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.AddField(
            model_name='profileaction',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wouldyou.Player'),
        ),
        migrations.AddField(
            model_name='profileaction',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wouldyou.Profile'),
        ),
        migrations.AddField(
            model_name='profileaction',
            name='profileset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wouldyou.ProfileSet'),
        ),
        migrations.AddField(
            model_name='profileaction',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wouldyou.Verb'),
        ),
        migrations.AddField(
            model_name='playerset',
            name='players',
            field=models.ManyToManyField(to='wouldyou.Player'),
        ),
        migrations.AddField(
            model_name='playeraction',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='wouldyou.Player'),
        ),
        migrations.AddField(
            model_name='playeraction',
            name='friendset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wouldyou.PlayerSet'),
        ),
        migrations.AddField(
            model_name='playeraction',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wouldyou.Player'),
        ),
        migrations.AddField(
            model_name='playeraction',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wouldyou.Verb'),
        ),
    ]
