# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wouldyou', '0015_auto_20160825_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='request',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
