# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wouldyou', '0017_auto_20160825_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeraction',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='wouldyou.Player'),
        ),
        migrations.AlterField(
            model_name='profileaction',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wouldyou.Profile'),
        ),
        migrations.AlterField(
            model_name='profileset',
            name='name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
