# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wouldyou', '0019_auto_20160826_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='player',
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
