# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wouldyou', '0020_auto_20160826_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerset',
            name='player_id_set',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
