# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wouldyou', '0025_auto_20160831_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='profileset',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
