# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 15:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wouldyou', '0026_auto_20160901_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerbDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='verb',
            name='action',
            field=models.CharField(default='', max_length=30, verbose_name='Facebook action name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verbdescription',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wouldyou.Verb'),
        ),
    ]
