# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wouldyou', '0027_auto_20160901_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='match_text',
            field=models.CharField(default='', max_length=200, verbose_name='Text to show when two players match'),
            preserve_default=False,
        ),
    ]
